### PR TITLE
add serde to bracket-color for bevy

### PR DESCRIPTION
**Pull request by lecoqjacob**

### CODE REVIEW

**Comment by thebracket** [comment]
That looks like a good idea. I wonder if it should be optional? Not everyone uses serde, and lots of people complain about its compile times. I'll try and look at this in the next day or two; the day-job is eating my time right now.

**Comment by lecoqjacob** [comment]
Ah I didn't realize the long compile times with serde. In that case it should probably be a feature flag! I can bump that tonight for you

**Comment by lecoqjacob** [comment]
Updaed to make serde a feature flag on `bracket-bevy` :)

**Comment by thebracket** [comment]
This looks good, and tested ok locally - so I'll go ahead and merge. Thanks!

**Pull request merged**
